# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVcmukffRbaAc-MpOF9FsAlqqiGqSQAD
"""

print('hello world')

name = "Jasper Leen"
age = "21"

print(name)
print(age)

x = 5
y = 10

print(x+y)

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df['species'] = iris.target_names[iris.target]
df.head()



print("Nummber of observations:", df.shape[0])
print("Number of features:", df.shape[1]-1)

df.info()

df.describe()

plt.figure(figsize=(8,6))
plt.scatter(df['petal length (cm)'],
            df['petal width (cm)']
            )
plt.xlabel('petal length (cm)')
plt.ylabel('petal width (cm)')
plt.title('petal length vs petal width')
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(
    df["sepal length (cm)"],
    df["sepal width (cm)"]
)

plt.xlabel("sepal length (cm)")
plt.ylabel("sepal width (cm)")
plt.title("Sepal Length vs Sepal Width")

plt.show()

plt.figure(figsize=(8,6))

for species in df["species"].unique():
  subset=df[df["species"] == species]
plt.scatter(
  subset["sepal length (cm)"],
  subset["sepal width (cm)"],
  label = species
  )

plt.xlabel("Sepal length (cm)")
plt.xlabel("Sepal width (cm)")
plt.title("Iris Species Distribution")

plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

for species in df["species"].unique():
    subset = df[df["species"] == species]
    plt.scatter(
        subset["petal length (cm)"],
        subset["petal width (cm)"],
        label=species,
    )

plt.xlabel("petal length (cm)")
plt.ylabel("petal width (cm)")
plt.title("iris species based on petal measurements😍")
plt.legend()

plt.show()

x = iris.data
y = iris.target

print("X shape:", x.shape)
print("Y shape:", y.shape)

X_train, X_train, y_train, y_train = train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)

print("Actual: ")
print(y_train)
print("\nPredicted: ")
print(y_pred)

accuracy = accuracy_score(y_train, y_pred)
print("Accuracy:", accuracy)